### ISSUE TITLE
Errors and warnings during build on Arch Linux

### ISSUE THREAD

**Issue by joni999** [vpinball/vpinball#2412]
**Describe the bug**
Error & warnings during build on Arch Linux with gcc 15.1.1 20250425

log of the build:
https://pastebin.com/8mfmdtuu

**To Reproduce**
1) platforms/linux-x64/external.sh
2) cmake -DCMAKE_BUILD_TYPE=Release -B build
3) cmake --build build -- -j$(nproc)

**Expected behavior**
No errors and less/no warnings

**Versions & Settings**
 - VPX: bleeding edge: [e039477](https://github.com/vpinball/vpinball/commit/e039477b5387efb27c106130faa63fc716a9a759)
 - on Arch Linux
 - gcc 15.1.1 20250425

**Comment by jsm174** [comment]
from your log. Looks like we might need to include <algorithm> 

```
 15%] Building CXX object CMakeFiles/FlexDMDPlugin.dir/plugins/flexdmd/actors/GIFImage.cpp.o
/home/joni/git/vpinball/plugins/pup/PUPPlaylist.cpp: In constructor ‘PUPPlaylist::PUPPlaylist(PUPManager*, const std::string&, const std::string&, bool, int, float, int)’:
/home/joni/git/vpinball/plugins/pup/PUPPlaylist.cpp:75:9: error: ‘sort’ is not a member of ‘std’; did you mean ‘sqrt’?
   75 |    std::sort(m_files.begin(), m_files.end());
```

As far as the warnings go, those wine ones will be difficult to fix.

**Comment by toxieainc** [comment]
The wine ones would need to be fixed on the wine repo, so if you're brave enough ;) then that would need to go there : https://gitlab.winehq.org/wine/wine

**Comment by joni999** [comment]
Most of the notes and warnings don't happen when I build wine from their current source - you use an older wine version (or older headers), right?
https://github.com/vpinball/vpinball/tree/master/standalone/inc/wine/include
(10.2 and older if I see correctly)

**Comment by joni999** [comment]
Opened a bug report on the wine bug tracker for the few notes & warnings that are still present when compiling wine from up to date sources:
https://bugs.winehq.org/show_bug.cgi?id=58226

I hope it's okay if I close this issue as all warnings on your side have been fixed

**Comment by jsm174** [comment]
The version of wine isn't really relevant. (I keep an eye on it everyday.)  We upgrade the source from time to time especially when something changes in `oleaut` or `vbscript`.

When your compiling wine directly, they could have all kinds of flags set to disable/enable some of the warnings. I really don't know.

We keep a patch file, just to show what we've changed to get this all to work: 

https://github.com/vpinball/vpinball/blob/master/standalone/inc/wine/wine-41abefccebf2729a70be9ec7bdb1c6226a56e369.patch
